### PR TITLE
Added action to run or schedule job

### PR DESCRIPTION
**Pull request by johnsca**

### CODE REVIEW

**Comment by andrewdmcleod** [comment]
When attempting to deploy this branch I get the following error:

unit-resmgr-0[8199]: 2016-05-17 04:10:24 INFO unit.resmgr/0.namenode-relation-changed logger.go:40   File "/var/lib/juju/agents/unit-resmgr-0/charm/reactive/resourcemanager.py", line 72, in send_info
unit-resmgr-0[8199]: 2016-05-17 04:10:24 INFO unit.resmgr/0.namenode-relation-changed logger.go:40     slaves = [node['host'] for node in nodemanager.nodes()]
unit-resmgr-0[8199]: 2016-05-17 04:10:24 INFO unit.resmgr/0.namenode-relation-changed logger.go:40   File "/var/lib/juju/agents/unit-resmgr-0/charm/reactive/resourcemanager.py", line 72, in <listcomp>
unit-resmgr-0[8199]: 2016-05-17 04:10:24 INFO unit.resmgr/0.namenode-relation-changed logger.go:40     slaves = [node['host'] for node in nodemanager.nodes()]
unit-resmgr-0[8199]: 2016-05-17 04:10:24 INFO unit.resmgr/0.namenode-relation-changed logger.go:40 TypeError: string indices must be integers
unit-resmgr-0[8199]: 2016-05-17 04:10:24 ERROR juju.worker.uniter.operation runhook.go:107 hook "namenode-relation-changed" failed: exit status 1

**Comment by johnsca** [comment]
That error seems unrelated to this change and seems to be due to this branch being out of date with the changes that have been made with the interface layers since this was created (changing `nodes()` to return a list of node names instead of a dict).

I'll rebase against master and force push it, which should resolve this.

**Comment by johnsca** [comment]
Updated.  You'll need to either delete the branch locally and pull again, or do a `git fetch` / `git reset --hard` to the origin version of the branch, since it was a rebase / force-push.

**Comment by andrewdmcleod** [comment]
I've tested this using the following jar:
https://github.com/omalley/hadoop-gpl-compression/raw/master/lib/hadoop-mapred-examples-0.21.0-dev.jar

Single-run works fine without any params, and with each param (compression=lzo and extra test param)

param: cron="*/5 * * * *" fails with
ERROR YAML error: did not find expected alphabetic or numeric character

inserting a random character at the start of the param argument submits the job but fails as it is an invalid cron string.
(juju 1.25.5-trusty-amd64)

**Comment by johnsca** [comment]
@andrewdmcleod To submit the cron arg, you need to give the `--string-args` param to force Juju to stop trying to interpret the value.

**Comment by andrewdmcleod** [comment]
with --string-args the job is submitted successfully, and the cron entry is also created successfully.

LGTM +1

**Pull request merged**
